version: '3'
services:
  node:
    image: victorjsv/orbis-training-docker:2.0.0
    volumes: 
      - .:/app
    ports:
      - 3030:3030
      - 35729:35729
    command: npm start
  test:
    image: node:10.10.0-slim
    command: curl http://node:3030/
    depends_on:
      - node
